import type { TradeIdea, MacroRegime } from '@/types';

export const FALLBACK_REGIME: MacroRegime = {
  label: 'Active Conflict',
  level: 'CRITICAL',
  subtitle: 'Strait of Hormuz',
  summary: 'Active military operations in the Strait of Hormuz region with direct implications for global energy supply and shipping routes.',
};

export const FALLBACK_TRADES: TradeIdea[] = [
  {
    id: 'fb_drs',
    ticker: 'DRS',
    fullName: 'Leonardo DRS Inc',
    direction: 'LONG',
    conviction: 8,
    orderType: '2ND_ORDER',
    categories: ['DEFENSE'],
    timeHorizon: 'WEEKS',
    horizonLabel: '2-4 Weeks',
    currentPrice: 32.5,
    priceChange: 4.2,
    thesis: 'Escalating maritime conflict in the Strait of Hormuz drives sustained demand for naval defense electronics and infrared countermeasure systems.',
    causalChain: [
      { label: 'Iran-linked forces target commercial shipping in Hormuz', sentiment: 'negative' },
      { label: 'US/allied naval deployments surge in Persian Gulf', sentiment: 'negative' },
      { label: 'Pentagon accelerates procurement of naval defense systems', sentiment: 'positive' },
      { label: 'DRS naval electronics division sees order acceleration', sentiment: 'positive' },
    ],
    pricedIn: 'General defense sector uplift from Middle East tensions',
    edge: 'Market underpricing the specific naval electronics demand from Hormuz-focused operations vs. broader defense rotation',
    riskReward: { upside: 20, downside: 8, ratio: '2.5:1' },
    entry: 'On any pullback to $30-31 range or at current levels',
    invalidation: 'Ceasefire agreement or de-escalation in Hormuz',
    breakers: ['Diplomatic breakthrough reducing naval presence', 'Defense budget sequestration', 'Broad market risk-off event'],
    platforms: [{ name: 'Robinhood', instrument: 'DRS' }, { name: 'Trading212', instrument: 'DRS' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_wheat',
    ticker: 'ZW1!',
    fullName: 'CBOT Wheat Futures',
    direction: 'LONG',
    conviction: 7,
    orderType: '3RD_ORDER',
    categories: ['AGRICULTURE', 'COMMODITIES'],
    timeHorizon: 'WEEKS',
    horizonLabel: '1-3 Weeks',
    currentPrice: 580,
    priceChange: 2.8,
    thesis: 'Prolonged Strait of Hormuz disruption redirects global shipping, increasing transit times for Black Sea grain exports and tightening wheat supply.',
    causalChain: [
      { label: 'Hormuz conflict disrupts global shipping lanes', sentiment: 'negative' },
      { label: 'Insurance costs spike for Middle East-adjacent routes', sentiment: 'negative' },
      { label: 'Grain shipments from Black Sea rerouted via longer paths', sentiment: 'negative' },
      { label: 'Effective wheat supply tightens, futures rise', sentiment: 'positive' },
    ],
    pricedIn: 'Direct oil supply disruption narrative',
    edge: 'Third-order effect on grain logistics largely ignored by commodity desks focused on energy',
    riskReward: { upside: 15, downside: 6, ratio: '2.5:1' },
    entry: 'At current levels with stop below 550',
    invalidation: 'Rapid conflict resolution or alternative shipping corridors established',
    breakers: ['Quick ceasefire reopening Hormuz', 'Bumper wheat harvest in major producing regions', 'Strong USD crushing commodity prices'],
    platforms: [{ name: 'Robinhood', instrument: 'WEAT' }, { name: 'Ostrium', instrument: 'WHEAT-USD' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_hack',
    ticker: 'HACK',
    fullName: 'ETFMG Prime Cyber Security ETF',
    direction: 'LONG',
    conviction: 7,
    orderType: '2ND_ORDER',
    categories: ['DEFENSE'],
    timeHorizon: 'MONTHS',
    horizonLabel: '1-3 Months',
    currentPrice: 62.8,
    priceChange: 1.5,
    thesis: 'Escalating geopolitical tensions drive significant increase in state-sponsored cyber attacks, accelerating government and enterprise cybersecurity spending.',
    causalChain: [
      { label: 'Iran-Israel conflict intensifies kinetic + cyber domains', sentiment: 'negative' },
      { label: 'State-sponsored cyber attacks on critical infrastructure spike', sentiment: 'negative' },
      { label: 'Governments mandate accelerated cybersecurity upgrades', sentiment: 'positive' },
      { label: 'Cybersecurity firms see order book expansion', sentiment: 'positive' },
    ],
    pricedIn: 'Baseline cybersecurity growth narrative',
    edge: 'Geopolitical cyber escalation creates step-change in urgency beyond normal growth trajectory',
    riskReward: { upside: 18, downside: 7, ratio: '2.6:1' },
    entry: 'At current levels or on pullback to $60',
    invalidation: 'De-escalation in cyber warfare domain',
    breakers: ['Major diplomatic resolution', 'Tech sector broad selloff', 'Shift to purely kinetic conflict'],
    platforms: [{ name: 'Robinhood', instrument: 'HACK' }, { name: 'Trading212', instrument: 'HACK' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_zim',
    ticker: 'ZIM',
    fullName: 'ZIM Integrated Shipping Services',
    direction: 'LONG',
    conviction: 8,
    orderType: '1ST_ORDER',
    categories: ['SHIPPING'],
    timeHorizon: 'DAYS',
    horizonLabel: '3-7 Days',
    currentPrice: 28.3,
    priceChange: 5.1,
    thesis: 'Hormuz disruption forces container shipping reroutes around Africa, dramatically increasing effective shipping capacity utilization and freight rates.',
    causalChain: [
      { label: 'Military operations make Hormuz transit dangerous', sentiment: 'negative' },
      { label: 'Shipping companies reroute via Cape of Good Hope', sentiment: 'negative' },
      { label: 'Voyage lengths increase 30-40%, absorbing excess capacity', sentiment: 'positive' },
      { label: 'Spot freight rates surge, ZIM earnings outlook improves', sentiment: 'positive' },
    ],
    pricedIn: 'Some Hormuz risk premium already in shipping names',
    edge: 'Duration of disruption underestimated — market pricing short conflict but logistics chains take months to normalize',
    riskReward: { upside: 25, downside: 10, ratio: '2.5:1' },
    entry: 'At current levels, momentum trade',
    invalidation: 'Hormuz reopening or naval escort convoys established',
    breakers: ['Rapid ceasefire', 'Naval convoy system negating rerouting need', 'Global recession crushing shipping demand'],
    platforms: [{ name: 'Robinhood', instrument: 'ZIM' }, { name: 'Trading212', instrument: 'ZIM' }],
    isCrowded: true,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_eem_short',
    ticker: 'EEM',
    fullName: 'iShares MSCI Emerging Markets ETF',
    direction: 'SHORT',
    conviction: 6,
    orderType: '2ND_ORDER',
    categories: ['EMERGING_MARKETS'],
    timeHorizon: 'WEEKS',
    horizonLabel: '1-2 Weeks',
    currentPrice: 57.2,
    priceChange: -3.2,
    thesis: 'Middle East escalation triggers capital flight from emerging markets as risk appetite collapses and dollar strengthens on safe-haven flows.',
    causalChain: [
      { label: 'Active conflict raises global risk premiums', sentiment: 'negative' },
      { label: 'Capital rotates to safe havens (USD, Treasuries, gold)', sentiment: 'negative' },
      { label: 'EM currencies weaken as USD strengthens', sentiment: 'negative' },
      { label: 'EM equities face double hit of outflows + currency drag', sentiment: 'negative' },
    ],
    pricedIn: 'Some initial EM weakness already priced',
    edge: 'Second-wave EM selling typically occurs 1-2 weeks after initial shock as fund redemptions cascade',
    riskReward: { upside: 12, downside: 5, ratio: '2.4:1' },
    entry: 'Short at current levels via puts or inverse ETF',
    invalidation: 'Rapid de-escalation or coordinated EM central bank intervention',
    breakers: ['Ceasefire announcement', 'Fed emergency rate cut supporting risk assets', 'China stimulus offsetting EM outflows'],
    platforms: [{ name: 'Robinhood', instrument: 'EEM' }, { name: 'Trading212', instrument: 'EEM' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_uso',
    ticker: 'USO',
    fullName: 'United States Oil Fund',
    direction: 'LONG',
    conviction: 9,
    orderType: 'CROWDED',
    categories: ['ENERGY', 'COMMODITIES'],
    timeHorizon: 'DAYS',
    horizonLabel: '1-5 Days',
    currentPrice: 78.5,
    priceChange: 6.8,
    thesis: 'Direct Hormuz disruption threatens 20% of global oil transit. Obvious first-order trade but magnitude of supply shock still underpriced.',
    causalChain: [
      { label: 'Military conflict in Strait of Hormuz', sentiment: 'negative' },
      { label: '~20M barrels/day of oil transit at risk', sentiment: 'negative' },
      { label: 'Global oil supply shock drives crude above $100', sentiment: 'positive' },
    ],
    pricedIn: 'General Middle East risk premium already elevated',
    edge: 'Market pricing temporary disruption — actual supply impact may persist weeks/months',
    riskReward: { upside: 15, downside: 8, ratio: '1.9:1' },
    entry: 'At market, this is a momentum play',
    invalidation: 'Ceasefire or confirmation that oil transit is unaffected',
    breakers: ['Diplomatic resolution', 'SPR release announcement', 'Global demand destruction'],
    platforms: [{ name: 'Robinhood', instrument: 'USO' }, { name: 'Ostrium', instrument: 'WTI-USD' }],
    isCrowded: true,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
];
