import type { TradeIdea, MacroRegime } from '@/types';

export const FALLBACK_REGIME: MacroRegime = {
  label: 'Active Conflict',
  level: 'CRITICAL',
  subtitle: 'Strait of Hormuz',
  summary: 'Active military operations in the Strait of Hormuz region with direct implications for global energy supply and shipping routes.',
};

export const FALLBACK_TRADES: TradeIdea[] = [
  {
    id: 'fb_drs',
    ticker: 'DRS',
    fullName: 'Leonardo DRS Inc',
    direction: 'LONG',
    conviction: 8,
    orderType: '2ND_ORDER',
    categories: ['DEFENSE'],
    timeHorizon: 'WEEKS',
    horizonLabel: '2-4 Weeks',
    currentPrice: 32.5,
    priceChange: 4.2,
    thesis: 'Hormuz conflict drives a step-change in naval electronics procurement. DRS supplies 70%+ of US Navy infrared countermeasure systems and electronic warfare suites. Pentagon supplemental funding for naval ops historically flows within 2-3 weeks of sustained deployment — DRS book-to-bill ratio jumped 1.4x during the 2019 Gulf tanker crisis.',
    causalChain: [
      { label: 'Iran-linked forces target commercial shipping — 3+ tanker incidents trigger CENTCOM escalation', sentiment: 'negative' },
      { label: 'US deploys 2nd carrier strike group to Persian Gulf (precedent: 2019 saw CSG-12 + CSG-5 within 10 days)', sentiment: 'negative' },
      { label: 'Pentagon submits $2-4B supplemental request for naval readiness (2019 supplemental was $1.8B for lesser threat)', sentiment: 'positive' },
      { label: 'DRS naval electronics backlog expands 15-25% — IRCMs, EW jammers, radar systems on accelerated delivery', sentiment: 'positive' },
    ],
    pricedIn: 'Broad defense sector +3-5% rotation already occurred. Market treating DRS as generic defense beta, not pricing the naval-specific demand surge.',
    edge: 'The Street models DRS at 12-14% revenue growth (consensus). Naval supplemental funding historically adds 400-600bps to top-line within 2 quarters. The catalyst: first Pentagon supplemental budget request or emergency procurement order leak.',
    riskReward: { upside: 22, downside: 8, ratio: '2.8:1' },
    entry: 'Buy below $31.50 on any broad market pullback; initial size 2-3% of book. Add above $35 on confirmed Pentagon order flow.',
    invalidation: 'Exit if US pulls carrier group from Gulf (signals de-escalation) or DRS loses key contract rebid. Hard stop at $28.50 (-12%).',
    breakers: [
      'Surprise ceasefire brokered by China (~15% probability) — would unwind defense premium within 1 week',
      'Defense budget sequestration fight in Congress delays supplemental by 3+ months',
      'Broad equity selloff >10% dragging all small-caps regardless of fundamentals',
    ],
    platforms: [{ name: 'Robinhood', instrument: 'DRS' }, { name: 'Trading212', instrument: 'DRS' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_wheat',
    ticker: 'ZW1!',
    fullName: 'CBOT Wheat Futures',
    direction: 'LONG',
    conviction: 7,
    orderType: '3RD_ORDER',
    categories: ['AGRICULTURE', 'COMMODITIES'],
    timeHorizon: 'WEEKS',
    horizonLabel: '1-3 Weeks',
    currentPrice: 580,
    priceChange: 2.8,
    thesis: 'Hormuz conflict forces global shipping reroutes that compress Black Sea grain export capacity by 15-20%. Ukraine/Russia export 30% of global wheat — even a 10-day shipping disruption tightens the global stocks-to-use ratio from 33% to below 30%, the threshold that triggered the 2022 wheat spike to $12.50/bushel.',
    causalChain: [
      { label: 'Hormuz conflict spills into broader Gulf maritime insurance crisis — war-risk premiums spike 300-500bps across Middle East routes', sentiment: 'negative' },
      { label: 'Shipping companies reroute via Cape of Good Hope, adding 12-15 days to Asia-bound grain cargoes (same rerouting during Red Sea crisis 2024)', sentiment: 'negative' },
      { label: 'Effective vessel capacity drops 15-20% — fewer ships available for Black Sea grain lifts as fleet absorbed on longer routes', sentiment: 'negative' },
      { label: 'CBOT wheat futures reprice from $5.80 toward $6.50-7.00 as global stocks-to-use ratio tightens below 30%', sentiment: 'positive' },
    ],
    pricedIn: 'Market focused entirely on direct oil supply disruption. Wheat positioning is net-short (CFTC spec shorts at 52-week high). Zero grain-logistics premium in the curve.',
    edge: 'Commodity desks are 100% focused on energy. The third-order grain logistics effect is invisible to them. CFTC data shows managed money net short wheat — any covering creates a violent squeeze. Catalyst: first USDA or IGC report flagging shipping delays on Black Sea grain.',
    riskReward: { upside: 18, downside: 7, ratio: '2.6:1' },
    entry: 'Buy WEAT ETF below $22.00 or wheat futures at $5.75-5.85. Size 1.5-2% of book. This is a convexity trade — small position, large payoff.',
    invalidation: 'Exit if Hormuz conflict resolves within 5 days (insufficient time for grain logistics to tighten) or if USDA reports unexpected inventory build. Stop below $5.40.',
    breakers: [
      'Quick ceasefire reopening Hormuz within 1 week (~20% probability) — grain logistics never actually disrupted',
      'Bumper Southern Hemisphere harvest (Australia, Argentina) offsetting any supply tightness',
      'USD rally above DXY 108 crushing all commodity prices regardless of fundamentals',
    ],
    platforms: [{ name: 'Robinhood', instrument: 'WEAT' }, { name: 'Ostrium', instrument: 'WHEAT-USD' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_hack',
    ticker: 'HACK',
    fullName: 'ETFMG Prime Cyber Security ETF',
    direction: 'LONG',
    conviction: 7,
    orderType: '2ND_ORDER',
    categories: ['DEFENSE'],
    timeHorizon: 'MONTHS',
    horizonLabel: '1-3 Months',
    currentPrice: 62.8,
    priceChange: 1.5,
    thesis: 'Every major Iran-Israel escalation since 2020 triggered a 40-60% spike in state-sponsored cyber attacks within 2 weeks (Mandiant data). Post-attack, government cybersecurity spending accelerates — the 2023 Iran-linked water utility attacks drove a $1.2B emergency CISA appropriation. Current escalation is 3-5x larger in kinetic scope, implying proportionally larger cyber response.',
    causalChain: [
      { label: 'Iran activates full cyber warfare capabilities — APT33, APT42, MuddyWater target critical infrastructure (historical: 2022 Albania attacks hit within 48hrs of diplomatic break)', sentiment: 'negative' },
      { label: 'State-sponsored attacks on US/EU critical infrastructure spike 40-60% (Mandiant baseline from 2023 Iran-Israel escalation)', sentiment: 'negative' },
      { label: 'White House issues emergency cybersecurity directive — mandates 90-day compliance for critical infrastructure operators', sentiment: 'positive' },
      { label: 'CrowdStrike, Palo Alto, Fortinet see 20-30% acceleration in enterprise pipeline — reflected in HACK ETF constituents', sentiment: 'positive' },
    ],
    pricedIn: 'Baseline cybersecurity secular growth narrative (12-15% CAGR). Market NOT pricing step-change in urgency from state-sponsored escalation.',
    edge: 'Street models cybersecurity on steady-state demand curves. Geopolitical cyber escalation creates non-linear demand spikes — the 2023 CISA emergency appropriation was approved in 3 weeks vs. normal 6-month cycle. Catalyst: first confirmed Iranian cyber attack on Western infrastructure (water, grid, financial system).',
    riskReward: { upside: 20, downside: 7, ratio: '2.9:1' },
    entry: 'Buy HACK at $62 or below. Size 2% of book. Consider adding CrowdStrike (CRWD) as single-stock overlay at $340 for higher beta.',
    invalidation: 'Exit if conflict de-escalates to purely kinetic domain (no cyber spillover after 3 weeks) or if HACK breaks below $58 (200-day MA). Hard stop at -10%.',
    breakers: [
      'Major diplomatic resolution removing cyber escalation risk (~10% probability in near-term)',
      'Broad tech sector correction >8% dragging HACK despite strong fundamentals',
      'Shift to purely kinetic warfare with no cyber component — rare but possible if Iran prioritizes conventional forces',
    ],
    platforms: [{ name: 'Robinhood', instrument: 'HACK' }, { name: 'Trading212', instrument: 'HACK' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_zim',
    ticker: 'ZIM',
    fullName: 'ZIM Integrated Shipping Services',
    direction: 'LONG',
    conviction: 8,
    orderType: '1ST_ORDER',
    categories: ['SHIPPING'],
    timeHorizon: 'DAYS',
    horizonLabel: '3-7 Days',
    currentPrice: 28.3,
    priceChange: 5.1,
    thesis: 'Hormuz rerouting adds 12-15 days to Asia-Europe voyages via Cape of Good Hope, absorbing 25-30% of global container capacity. During the Red Sea crisis (2024), ZIM revenues jumped 86% QoQ when shipping rates tripled. The Hormuz disruption is 3-4x larger in trade volume terms — Drewry WCI could reprice from $2,800 to $6,000-8,000 within 2 weeks.',
    causalChain: [
      { label: 'Hormuz transit becomes untenable — insurers suspend war-risk coverage for strait passage (same playbook as Red Sea 2024)', sentiment: 'negative' },
      { label: 'Container lines reroute 100% of Hormuz traffic via Cape of Good Hope — adds 12-15 sailing days per voyage', sentiment: 'negative' },
      { label: 'Effective global fleet capacity drops 25-30% as ships absorbed on longer routes (Red Sea rerouting absorbed ~15% — Hormuz is 2x the volume)', sentiment: 'positive' },
      { label: 'Spot freight rates surge 150-200% within 2 weeks — ZIM with 60% spot exposure sees immediate earnings uplift', sentiment: 'positive' },
    ],
    pricedIn: 'Market pricing some shipping risk — ZIM up 5% already. But current price implies Drewry WCI at ~$3,500, far below the $6,000-8,000 likely if disruption lasts >2 weeks.',
    edge: 'Street consensus: disruption lasts 1-2 weeks, Drewry WCI peaks at $3,500-4,000. Historical pattern says otherwise — Red Sea disruption lasted 8+ months. ZIM at $28 prices a mild scenario. The repricing catalyst: Drewry weekly rate print showing $4,000+ or first major container line announcing official Hormuz avoidance.',
    riskReward: { upside: 30, downside: 12, ratio: '2.5:1' },
    entry: 'Buy below $27.50 on any intraday weakness; this is a momentum trade — don\'t wait for perfect entry. Size 2-3% of book. Add above $34 on confirmed rate hikes.',
    invalidation: 'Exit if Hormuz reopens with naval escort convoy system (kills the rerouting thesis) or if Drewry WCI fails to break above $3,500 within 10 days. Hard stop at $24.50 (-13%).',
    breakers: [
      'Rapid ceasefire within 72 hours (~15% probability) before shipping reroutes fully materialize',
      'US/allied naval convoy system established through the strait — negates need for rerouting and collapses rate premium',
      'Global recession fear triggers demand destruction exceeding the supply shock — container volumes collapse',
    ],
    platforms: [{ name: 'Robinhood', instrument: 'ZIM' }, { name: 'Trading212', instrument: 'ZIM' }],
    isCrowded: true,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_eem_short',
    ticker: 'EEM',
    fullName: 'iShares MSCI Emerging Markets ETF',
    direction: 'SHORT',
    conviction: 6,
    orderType: '2ND_ORDER',
    categories: ['EMERGING_MARKETS'],
    timeHorizon: 'WEEKS',
    horizonLabel: '1-2 Weeks',
    currentPrice: 57.2,
    priceChange: -3.2,
    thesis: 'Middle East escalation triggers the classic EM capital flight playbook — DXY rally + VIX spike + EM fund redemptions create a self-reinforcing outflow cycle. Historical pattern: 2019 Gulf tanker crisis saw EEM drop 8.2% over 3 weeks as EM FX weakened 4-6% vs. USD. Current conflict is larger in scope, and EM positioning is more extended (IIF data shows $14B EM equity inflows YTD — ripe for reversal).',
    causalChain: [
      { label: 'Active Hormuz conflict drives VIX from 18 to 28-32 range (precedent: Russia-Ukraine VIX spiked to 37 within 1 week)', sentiment: 'negative' },
      { label: 'Capital rotates to safe havens — USD, Treasuries, gold. DXY rallies 2-4% in 2 weeks (2019 Gulf crisis saw +2.8% DXY)', sentiment: 'negative' },
      { label: 'EM currencies weaken 3-6% vs. USD as carry trades unwind — Turkey, South Africa, Brazil hardest hit', sentiment: 'negative' },
      { label: 'EM equity fund redemptions cascade with 1-2 week lag — IIF data shows $14B YTD inflows now reversing', sentiment: 'negative' },
    ],
    pricedIn: 'Initial -3% EM selloff reflects day-one risk-off. NOT pricing the second-wave fund redemption cycle that historically occurs 7-14 days after initial shock.',
    edge: 'Day-one selloff is reflexive; the real damage comes in week 2-3 as fund redemptions force systematic selling. IIF flow data shows $14B EM equity inflows YTD — this is the fuel for the unwind. Catalyst: first major EM fund reporting redemption spike or EPFR weekly data showing $3B+ EM outflows.',
    riskReward: { upside: 14, downside: 6, ratio: '2.3:1' },
    entry: 'Short EEM via puts (buy Apr $55 puts at ~$1.50) or short via EUM inverse ETF. Size 1.5-2% of book. Put structure limits downside to premium paid.',
    invalidation: 'Exit if VIX drops back below 20 (signals risk-on return) or if coordinated EM central bank intervention announced (like 2018 EM CBs joint action). Stop on short at EEM $59.50 (+4%).',
    breakers: [
      'Rapid de-escalation with ceasefire (~15% probability) — VIX collapses, USD weakens, EM bounces violently',
      'Fed emergency rate cut or dovish pivot supporting risk assets globally',
      'China announces major stimulus package ($500B+) that overwhelms EM outflow pressure',
    ],
    platforms: [{ name: 'Robinhood', instrument: 'EEM' }, { name: 'Trading212', instrument: 'EEM' }],
    isCrowded: false,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
  {
    id: 'fb_uso',
    ticker: 'USO',
    fullName: 'United States Oil Fund',
    direction: 'LONG',
    conviction: 9,
    orderType: 'CROWDED',
    categories: ['ENERGY', 'COMMODITIES'],
    timeHorizon: 'DAYS',
    horizonLabel: '1-5 Days',
    currentPrice: 78.5,
    priceChange: 6.8,
    thesis: 'Hormuz handles 20.5M bbl/day — 21% of global seaborne oil and 33% of seaborne LNG. Even a partial closure removing 5-8M bbl/day exceeds the entire OPEC spare capacity of 4.5M bbl/day. WTI should trade $95-110 on a sustained disruption. Current $78 price implies market expects resolution within 5-7 days — US-Iran conflict history says otherwise (average duration: 6-8 weeks for significant escalations).',
    causalChain: [
      { label: '20.5M bbl/day of crude + 15% of global LNG transits Hormuz daily — any military action threatens the highest-volume energy chokepoint on earth', sentiment: 'negative' },
      { label: 'Even 25-40% flow reduction removes 5-8M bbl/day from market — exceeds total OPEC spare capacity (4.5M bbl/day) and SPR release capacity (1M bbl/day)', sentiment: 'negative' },
      { label: 'Physical crude market enters severe backwardation — Brent-Dubai spread blows out to $8-12 (vs. $2-3 normal), signaling real physical tightness', sentiment: 'positive' },
      { label: 'WTI reprices from $78 to $95-110 range as market shifts from "temporary disruption" to "sustained supply shock" pricing', sentiment: 'positive' },
    ],
    pricedIn: 'WTI at $78 prices a 5-7 day disruption with full Hormuz reopening. Options market shows 1-month 25-delta call skew at +1.8 (mildly bid for upside). SPR release expectations capping upside fears.',
    edge: 'CROWDED trade but still mispriced on DURATION. Street models assume quick resolution. The key math: OPEC spare capacity (4.5M bbl/day) + SPR drawdown (1M bbl/day) = 5.5M bbl/day max response. If disruption exceeds 6M bbl/day, physical market breaks. Catalyst: first satellite imagery showing tanker backlog at Hormuz approaches or Fujairah oil storage drawdown acceleration.',
    riskReward: { upside: 18, downside: 10, ratio: '1.8:1' },
    entry: 'Buy USO at market or WTI futures at $78-80. Size 3-4% of book — this is the highest-conviction trade but also the most crowded. Consider call spreads ($82/$95 1-month) for defined risk.',
    invalidation: 'Exit if Hormuz traffic resumes at >80% of normal volume for 3 consecutive days. Exit if Brent drops below $74 (signals market calling the bluff). Hard stop at -12%.',
    breakers: [
      'Surprise ceasefire + Hormuz transit resumption (~15% probability in first week) — oil gives back 60-70% of premium within 48hrs',
      'US announces massive SPR release (50M+ barrels) coordinated with IEA member states — caps upside at $90',
      'Global demand destruction from recession fears outweighs supply shock — unlikely near-term but possible if conflict triggers broader financial contagion',
    ],
    platforms: [{ name: 'Robinhood', instrument: 'USO' }, { name: 'Ostrium', instrument: 'WTI-USD' }],
    isCrowded: true,
    createdAt: new Date().toISOString(),
    newsIds: [],
  },
];
